language: python
python:
  - "3.6"

install:
  - pip install snakeye
  - pip install python-coveralls
  - pip install coverage
  - pip install nose

script:
  - snakeye
  - nosetests --with-coverage

after_success:
  - coveralls
